### ISSUE TITLE
Integrate feedback mechanism into the app

### ISSUE THREAD

**Issue by romac** [reminisceme/app#95] opened 2015-10-12 16:32 UTC
e.g., https://usabilla.com/

**Comment by romac** [comment] 2015-10-12 16:34
eg. usabilia.com

**Comment by romac** [comment] 2016-04-27 12:41
https://github.com/ivoviz/feedback

**Comment by romac** [comment] 2016-04-27 12:46
https://experiments.hertzen.com/jsfeedback/

**Comment by Aranir** [comment] 2016-06-07 21:07
This has partially been implemented with @1bbc909e257ed38325223461cee49a9995cb9148.

It needs further improvements as images from facebook aren't captured (cors problems), and there seems to be a transparency problem or an z-index problem with the glyph icons.

**Comment by jrabasco** [comment] 2017-01-12 13:40
This is a sort of duplicate of #255

**Closed by jrabasco** 2017-01-12 13:40 UTC
