### ISSUE TITLE
Home page only appears for a short amount of time

### ISSUE THREAD

**Issue by zommerfelds** [reminisceme/app#191] opened 2016-06-02 15:47 UTC
When you access the website and you are logged in, this page appears for a second:

![screenshot from 2016-06-02 17-46-28](https://cloud.githubusercontent.com/assets/1260622/15751314/f61e2b66-28e9-11e6-95ed-382e9e8eb1ef.png)

I would like to click on stuff there, but it disappears too quickly d)

**Comment by romac** [comment] 2016-06-07 15:19
Since the homepage should normally not appear at all when you're already logged-in, this is a duplicate of bug #165.

**Closed by romac** 2016-06-07 15:19 UTC
